/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;
import java.awt.Desktop;
import java.net.URI;

/**
 *
 * @author santi
 */
public class kfc extends javax.swing.JFrame {
    int b=100;
    String a= b+"";
    /**
     * Creates new form kfc
     */
    public kfc() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name_kfc = new javax.swing.JLabel();
        mesa_kfc = new javax.swing.JLabel();
        menu_fkc = new javax.swing.JButton();
        reservar_kfc = new javax.swing.JButton();
        numero_kfc = new javax.swing.JLabel();
        volver_kfc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        name_kfc.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        name_kfc.setText("KFC");

        mesa_kfc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mesa_kfc.setText("Mesas Disponibles");

        menu_fkc.setText("Descargar menu");
        menu_fkc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_fkcActionPerformed(evt);
            }
        });

        reservar_kfc.setText("Reservar");
        reservar_kfc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservar_kfcActionPerformed(evt);
            }
        });

        numero_kfc.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        numero_kfc.setForeground(new java.awt.Color(255, 0, 0));
        numero_kfc.setText(a);

        volver_kfc.setText("volver");
        volver_kfc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volver_kfcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(menu_fkc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reservar_kfc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mesa_kfc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(volver_kfc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(name_kfc, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(numero_kfc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name_kfc, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(volver_kfc, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(mesa_kfc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numero_kfc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153)
                .addComponent(menu_fkc)
                .addGap(63, 63, 63)
                .addComponent(reservar_kfc)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_fkcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_fkcActionPerformed
        this.abrirEnlaces("https://www.kentucky.com.do/menu/nuestro-menu");
    }//GEN-LAST:event_menu_fkcActionPerformed

    private void reservar_kfcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservar_kfcActionPerformed
        b-=1;
        a=b+"";
        numero_kfc.setText(a);
    }//GEN-LAST:event_reservar_kfcActionPerformed

    private void volver_kfcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volver_kfcActionPerformed
        menu c = new menu();
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_volver_kfcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kfc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kfc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kfc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kfc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kfc().setVisible(true);
            }
        });
    }
    public void abrirEnlaces(String URL){
        try {
            Desktop.getDesktop().browse(URI.create(URL));
        } catch (Exception e){
            e.getStackTrace();
        }
    }    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton menu_fkc;
    private javax.swing.JLabel mesa_kfc;
    private javax.swing.JLabel name_kfc;
    private javax.swing.JLabel numero_kfc;
    private javax.swing.JButton reservar_kfc;
    private javax.swing.JButton volver_kfc;
    // End of variables declaration//GEN-END:variables
}
